Room 2luxe
DemiGGV/mimino-team pull request #12
Opened 2023-01-29 14:31 UTC by Olena1010

Привіт.
Зробила все, окрім позиціонування великої фотки.
Поки не можу зрозуміти як її виставити згідно макету, а також не розумію що за відступ на ній же є на версії mobile.
Шукаю відповідь, можливо ти знаєш.

2023-01-29 15:45 UTC, DemiGGV requested changes
Все як ми казали при рев'ю через тімвьювер...

2023-01-29 21:23 UTC, DemiGGV requested changes

2023-01-29 21:23 UTC, DemiGGV commented on src/sass/components/hotel/_room-2luxe-hotel.scss
>      text-transform: uppercase;
назва шрифта - TimesNewRoman

2023-01-30 11:00 UTC, Olena1010 commented
скидання стилів прибрала
в кольорах виправила на змінні
лишні марджини поприбирала
пробіли в назвах шрифтів прибрала
div виправила на ul
на кнопці стоїть min-width, тому що просто width не працює
 .icon-room {display: flex;}  - добавила
 до флексконтейнера column-gap: 32px додала
 виправила: при збільшенні екрану картинка залишається урізаною 

 медіа запроси - не зрозуміла в чому саме є помилка, 
 хотіла би конкретніше, тому що у вашому прикладі мені не зрозуміло навіщо писати для десктопу те, що вже було раніше прописано для планшету і зі збільшенням екрану ці данні не змінюються ???…

**поставьте, пожалуйста, все медиазапросы в соответствующие селекторы, то есть:**

.room-luxe-logo {
text-transform: uppercase;
text-decoration: none;
font-family: 'FilmP3';
font-style: normal;
font-weight: 700;
font-size: 40px;
line-height: 1.07;
letter-spacing: 0.3em;
color: #494848;

@media screen and (min-width: 1280px) {
    font-size: 64px;
    margin-top: 4px;
    margin-bottom: 62px;
}
}

2023-01-30 19:24 UTC, Olena1010 commented
виправила все окрім тіні

2023-02-01 11:47 UTC, merged