html+css готово
DemiGGV/mimino-team pull request #13
Opened 2023-01-29 20:01 UTC by Olena1010

готово, перевіряй

2023-01-29 22:27 UTC, DemiGGV requested changes
Це цілком стосується і першої сторінки.

2023-01-29 22:27 UTC, DemiGGV commented on src/sass/components/hotel/_room-2x-hotel.scss
> +    min-width: 236px;
чому мін-віз?
Зробіть просто width: 236px

2023-01-29 22:27 UTC, DemiGGV commented on src/sass/components/hotel/_room-2x-hotel.scss
> +    margin-bottom: 20px;
Додати - display: flex;
Вам потрібно якось позіціонувати стрілки в контейнері

2023-01-29 22:27 UTC, DemiGGV commented on src/sass/components/hotel/_room-2x-hotel.scss
> +    margin-left: 32px;
не потрібно, додайте до флексконтейнера column-gap: 32px

2023-01-29 22:27 UTC, DemiGGV commented on src/sass/components/hotel/_room-2x-hotel.scss
> +    margin-right: auto;
в ціх стилях марджіни не потрібні, приберіть

2023-01-29 22:27 UTC, DemiGGV commented on src/sass/components/hotel/_room-2x-hotel.scss
> +    text-align: center;
сколько у вас ширина кнопки по макету? проверьте

2023-01-29 22:27 UTC, DemiGGV commented on src/sass/components/hotel/_room-2x-hotel.scss
> +.item-room {
ваша первая картинка на слайдере должна сохраняться "урезанной" при увеличении экрана, а не выплывать из-за границы на полный размер (это коментарий от проектного ментора)

2023-01-29 22:27 UTC, DemiGGV commented on src/sass/components/hotel/_room-2x-hotel.scss
> +@media screen and (max-width: 1023px) {
поставьте, пожалуйста, все медиазапросы в соответствующие селекторы, то есть:

.room-luxe-logo {
    text-transform: uppercase;
    text-decoration: none;
    font-family: 'FilmP3';
    font-style: normal;
    font-weight: 700;
    font-size: 40px;
    line-height: 1.07;
    letter-spacing: 0.3em;
    color: #494848;

    @media screen and (min-width: 1280px) {
        font-size: 64px;
        margin-top: 4px;
        margin-bottom: 62px;
    }
}

2023-01-30 11:16 UTC, Olena1010 commented
внесла зміни - можна перевіряти

2023-01-30 19:23 UTC, Olena1010 commented
виправила все окрім тіні

2023-02-01 11:58 UTC, merged