Header
DemiGGV/mimino-team pull request #6
Opened 2023-01-28 15:37 UTC by Elborn666

2023-01-29 16:01 UTC, DemiGGV requested changes

2023-01-29 16:01 UTC, DemiGGV commented on src/partials/header.html
>                      <a href="./index.html" class="header__logo" lang="en">mimino</a>
<a class="header__link" href="./restaurant.html">Ресторан
                                <svg class="header__link-icon">
                                    <use href="./images/sprite.svg#icon-phone"></use>
                                </svg>
</a>

Не надо атачить иконку к ссылке. На мобилке у тебя номер телефона сворачивается в иконку телефона.

2023-01-29 16:27 UTC, Elborn666 commented on src/sass/components/_header.scss
> +/*=================== Обнуление стилей ======================*/
исправлено

2023-01-29 16:28 UTC, Elborn666 commented on src/partials/header.html
>              <div class="header__body">
исправлено

2023-01-29 16:52 UTC, Elborn666 commented on src/partials/header.html
>                      <a href="./index.html" class="header__logo" lang="en">mimino</a>
Я не понимаю как это можно реализировать

2023-01-31 19:50 UTC, DemiGGV commented
Все буде добре!

2023-01-31 19:50 UTC, DemiGGV requested changes
Все буде добре!

2023-02-01 02:19 UTC, paladin3x commented
повиправляв цю трагедію.

2023-02-01 10:46 UTC, merged